# Generated by Django 5.2.11 on 2026-02-25 16:40

import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("desecapi", "0045_rr_unique_record_in_rrset"),
        ("desecapi", "0046_remove_rr_unique_record_in_rrset_and_more"),
    ]

    dependencies = [
        ("desecapi", "0044_alter_captcha_created_alter_domain_renewal_state_and_more"),
    ]

    operations = [
        django.contrib.postgres.operations.CreateExtension(
            name="pgcrypto",
        ),
        migrations.AddConstraint(
            model_name="rr",
            constraint=models.UniqueConstraint(
                models.F("rrset"),
                models.Func(
                    models.F("content"), models.Value("sha256"), function="digest"
                ),
                name="unique_record_in_rrset",
            ),
        ),
    ]
