# Generated by Django 5.2.11 on 2026-02-25 16:35

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0045_rr_unique_record_in_rrset"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rr",
            name="unique_record_in_rrset",
        ),
        CreateExtension("pgcrypto"),
        migrations.AddConstraint(
            model_name="rr",
            constraint=models.UniqueConstraint(
                models.F("rrset"),
                models.Func(
                    models.F("content"), models.Value("sha256"), function="digest"
                ),
                name="unique_record_in_rrset",
            ),
        ),
    ]
